- hosts: all
  connection: httpapi
  tasks:
    - name: Get all FMC domains
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: cra1

    - name: Get all network objects in first FMC domain
      cisco.fmcansible.fmc_configuration:
        operation: getAllNetworkObject
        path_params:
          domainUUID: '{{ cra1[0].uuid }}'
        register_as: cra

    - name: Create a network object for Cisco FMC
      cisco.fmcansible.fmc_configuration:
        operation: createNetworkObject
        path_params:
          domainUUID: '{{ cra1[0].uuid }}'
        data:
          name: CiscoFmcNetwork
          value: 3.3.3.0/24
          type: networkobject
